In [ ]:
#Question 1
import numpy

def arrays(arr):
    return numpy.array(arr[::-1],float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 5 4 7 8 6
[6. 8. 7. 4. 5. 2. 1.]


In [ ]:
#Question 2
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

7 8 9 6 3 2 1 4 5
[[7 8 9]
 [6 3 2]
 [1 4 5]]


In [ ]:
#Question 3
import numpy
m , n = input().split()
arr=[]
for i in range(int(m)):
    arr.append(input().strip().split())
arr1 = numpy.array(arr,int)
print(numpy.transpose(arr1))
print(arr1.flatten())

In [ ]:
#Question 4
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

In [ ]:
#Question 5
import numpy
a = tuple(map(int,input().split()))
a1 = numpy.zeros(a,dtype=numpy.int)
a2 = numpy.ones(a,dtype=numpy.int)
print(a1)
print(a2)

1 2
[[0 0]]
[[1 1]]


In [ ]:
#Question 6
import numpy
m , n = input().split()
numpy.set_printoptions(sign=' ')
print(numpy.eye(int(m),int(n)))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
#Question 7
import numpy
n = input().split()
list1 = []
list2 = []
for i in range(int(n[0])):
    a = map(int,input().split())
    list1.append(list(a))
for j in range(int(n[0])):
    b = map(int,input().split())
    list2.append(list(b))
a = numpy.array(list1)
b = numpy.array(list2)

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)


2 2
1 2 
2 5 
4 7 
7 8
[[ 5  9]
 [ 9 13]]
[[-3 -5]
 [-5 -3]]
[[ 4 14]
 [14 40]]
[[0 0]
 [0 0]]
[[1 2]
 [2 5]]
[[     1    128]
 [   128 390625]]


In [1]:
#Question 8
import numpy as np
np.set_printoptions(legacy='1.13')
arr = list(map(float,input().split()))
arr1 = np.array(arr)
print(np.floor(arr1))
print(np.ceil(arr1))
print(np.rint(arr1))


1.0 2.0 5.6 8.5 7.2
[ 1.  2.  5.  8.  7.]
[ 1.  2.  6.  9.  8.]
[ 1.  2.  6.  8.  7.]


In [2]:
#Question 9
import numpy
m , n = map(int,input().split())
arr=[]
for i in range(m):
    arr.append(list(map(int,input().split())))
arr1=numpy.array(arr)
print(numpy.prod(numpy.sum(arr1,axis=0)))

2 2
1 2 3
4 5 6
315


In [3]:
#Question 10
import numpy
m ,n =map(int,input().split())
arr=[]
for i in range(m):
    arr.append(list(map(int,input().split())))
arr1=numpy.array(arr)
print(numpy.max(numpy.min(arr1,axis=1)))

2 2
1 4 5
7 5 9
5


In [5]:
#Question 11
import numpy as np
m ,n =map(int,input().split())
arr=[]
for i in range(m):
    arr.append(list(map(int,input().split())))
arr1=np.array(arr)
print(np.mean(arr1,axis=1))
print(np.var(arr1,axis=0))
print(round(np.std(arr1),11))

2 2 
8 5 6
7 4 1
[ 6.33333333  4.        ]
[ 0.25  0.25  6.25]
2.26691175146


In [ ]:
#Question 12
import numpy
n = int(input())
A, B = [numpy.array([input().split() for _ in range(n)], int) for _ in range(2)]
print(numpy.dot(A, B))


4
1 2 3 6 4 
1 2 5 6 3
1 4 8 6 3
7 4 1 2 3
7 8 96 52 3


In [6]:
#Question 13
import numpy as np
arr1 = []
arr2=[]
arr1 = list(map(int,input().split()))
arr2 = list(map(int,input().split()))
arr3=np.array(arr1)
arr4=np.array(arr2)
print(np.inner(arr3,arr4))
print(np.outer(arr3,arr4))

2 3 6 5
7 8 2 4
70
[[14 16  4  8]
 [21 24  6 12]
 [42 48 12 24]
 [35 40 10 20]]


In [7]:
#Question 14
import numpy
P = list(map(float,input().split()))
x = int(input())
print (numpy.polyval(P,x))

1.0 8.2 7.3 5.0
1
21.5


In [10]:
#Question 15
import numpy as np
m = int(input())
arr=[]
for i in range(m):
    arr.append(list(map(float,input().strip().split())))
arr1=np.array(arr)
print(round(np.linalg.det(arr1),2))

2
1.1 1.1
1.1 1.1
0.0
